### PR TITLE
Better code refactoring: lookup.html

### PR DESCRIPTION
**Pull request by Harshit-Saxena**
Code refactoring. 

- Cause: The code was committed when the code editor was on ***wrap***

### CODE REVIEW

**Comment by pozil** [comment]
Hi @Harshit-Saxena, thanks for contributing however, I cannot accept your PR.
I'm using Prettier to automatically format the source code locally and verify formatting in the CI workflow (read more about it in [this blog post](https://developer.salesforce.com/blogs/2021/07/make-the-most-of-your-dx-projects-with-built-in-node-js-scripts)). Prettier ensures a consistent style across the codebase and your changes are unfortunately not in line with the current style settings (see failed task in CI workflow).

**Comment by Harshit-Saxena** [comment]
Hello @pozil, Thanks for responding. I know you're using prettier for auto-formatting, but Prettier's increasing the line is not helping. (+64) lines of code.

**Comment by pozil** [comment]
@Harshit-Saxena if you want to increase line length for your own local dev, you can set specify a `printWidth` property in `.prettierrc` (see [doc](https://prettier.io/docs/en/options.html)).

I'm not looking at changing this in the main repo because it would introduce noise in the commit changes but you could make your local change with your own settings and reformat just before pushing a PR.

**Comment by Harshit-Saxena** [comment]
@pozil I understand that. I will into the blog and the doc as well. Just started contributing to open source (YOE: 2) SF Dev.

**Pull request closed without merging**
