### PR TITLE
Added public custom key for iterators

### PR DESCRIPTION
**Pull request by Billdozer1547**

### CODE REVIEW

**Comment by Billdozer1547** [comment]
Added customKey API field to allow for use in template iterators so this can be used on a collection

**Comment by pozil** [comment]
Hi @Billdozer1547, thanks for the PR.
I'm not sure to understand the use case you'd like to cover here. Can you explain a bit more?

**Comment by Billdozer1547** [comment]
@pozil this is intended to make use easier in the <template for:each> tags, this gives a way to set a key within the loop and know which <c-lookup> is being edited.

Example:
`<template for:each={rows} for:item="row" for:index="index">
<td><c-lookup key={row.uuid} customKey={row.uuid} data-item={row.uuid} selection={initialSelection} errors={errors}
                        onsearch={handleAccountLookup} onselectionchange={handleSelectionChange}
                        label="" placeholder="Find Account" is-multi-entry={isMultiEntry}>
                    </c-lookup></td>`

So in the event you need to make multiple contacts from a single interface you can use this to set different accounts for each of them and know which <c-lookup> is triggering the event based on the customKey

**Comment by pozil** [comment]
Ok makes sense. Thx, will merge the PR.

**Pull request merged**
