### PR TITLE
wire default options feature

### PR DESCRIPTION
**Pull request by mdennin1**
added features to enable users to pass the selection property a salesforce id/string of salesforce ids delimted by a semi-colon (;) or an array of salesforce ids. if the wireDefaultOptions prop is set to true the component will invoke the getRecords wire adapter and then build the options with the response results enabling an automated selection default for salesforce records in the lookup

### CODE REVIEW

**Comment by mdennin1** [comment]
@pozil and/or others. I made some updates to the js file for the lookup component. please let me know what needs to be done to get these updates merged in. thank you

**Comment by pozil** [comment]
Hi @mdennin1 thanks for the contribution. I need to think about it because there are quite a lot of changes.
Can you start by running Prettier on your code so that I can see a cleaner diff?

**Comment by pozil** [comment]
Thanks for fixing the formatting, can you now also fix the linting errors by running ESLint (`npm run lint`)?

**Comment by mdennin1** [comment]
made some lint updates

**Pull request closed without merging**
