### PR TITLE
Add titles to selected items

### PR DESCRIPTION
**Pull request by zsturgess**
Helps improve usability when the item name may be longer than the lookup input allows for, as the user can now hover the selected item(s) to get their full names

### CODE REVIEW

**Comment by pozil** [comment]
Also a good contrib, thanks. Can you add the relevant tests?

**Comment by zsturgess** [comment]
Not so sure these tests are correct, but I couldn't find any rendering tests post-selection.

**Comment by pozil** [comment]
Thanks for the update @zsturgess. The tests are failing for formatting checks.
Can you run `npm run prettier` and commit the extra changes. This ensures coherent styling across all contribs.

**Comment by pozil** [comment]
Thanks @zsturgess, these tests are exactly what we need. I'm merging your PR.

FYI: CI is currently failing for contributions because of a security issue. It won't deploy/run code from a fork on a scratch org because it doesn't expose DX dev hub credentials in that context.

**Pull request merged**
