### PR TITLE
Hide the label element if it is omitted

### PR DESCRIPTION
**Pull request by zsturgess**
Allows the developer more flexibility to use this component in more locations by allowing the label element to be omitted entirely, if no label is provided.

### CODE REVIEW

**Comment by pozil** [comment]
Good contribution, thanks @zsturgess.

Can you add a test for that in `src/main/default/lwc/lookup/__tests__/lookupRendering.test.js` next to `it('renders label', () => {`?

**Comment by zsturgess** [comment]
Apologies for the force-push. Apparently accidentally added a bunch of things to this PR that I meant to keep on my fork only. 

Not really sure why the check is failing - `npm run test` works fine locally and all passes.

**Comment by pozil** [comment]
Thanks for the update @zsturgess. CI is failing on formatting checks.
Can you run `npm run prettier` and commit the extra changes. This enforces coherent code style across all contributions.

**Comment by pozil** [comment]
I've applied Prettier. I'll merge your PR. Thanks again.

**Pull request merged**
